CREATE TABLE ASIENTOS(
	[ASIENTOS_ID] [INT] NOT NULL,
	[COLUMNA_1_FILA_1] [VARCHAR] NULL,
	[COLUMNA_2_FILA_1] [VARCHAR] NULL,
	[COLUMNA_3_FILA_1] [VARCHAR] NULL,
	[COLUMNA_4_FILA_1] [VARCHAR] NULL,
	[COLUMNA_1_FILA_2] [VARCHAR] NULL,
	[COLUMNA_2_FILA_2] [VARCHAR] NULL,
	[COLUMNA_3_FILA_2] [VARCHAR] NULL,
	[COLUMNA_4_FILA_2] [VARCHAR] NULL,
	[COLUMNA_1_FILA_3] [VARCHAR] NULL,
	[COLUMNA_2_FILA_3] [VARCHAR] NULL,
	[COLUMNA_3_FILA_3] [VARCHAR] NULL,
	[COLUMNA_4_FILA_3] [VARCHAR] NULL,
	[COLUMNA_1_FILA_4] [VARCHAR] NULL,
	[COLUMNA_2_FILA_4] [VARCHAR] NULL,
	[COLUMNA_3_FILA_4] [VARCHAR] NULL,
	[COLUMNA_4_FILA_4] [VARCHAR] NULL,
	[COLUMNA_1_FILA_5] [VARCHAR] NULL,
	[COLUMNA_2_FILA_5] [VARCHAR] NULL,
	[COLUMNA_3_FILA_5] [VARCHAR] NULL,
	[COLUMNA_4_FILA_5] [VARCHAR] NULL
CONSTRAINT [PK_ASIENTOS_ID] PRIMARY KEY CLUSTERED 
(
	[ASIENTOS_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

SELECT * FROM ASIENTOS;

INSERT INTO ASIENTOS VALUES(1,' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ');

DROP TABLE ASIENTOS

EXEC pVerificadorDisponibilidad 1,1,1;

EXEC pReservador 1,1,1;

EXEC pHabilitador 1,1,1;


