CREATE TABLE [AVION](
	[AVION_ID] [int] NOT NULL,
	[CapPeso] [FLOAT] NOT NULL,
	[CapCombustible] [float] NOT NULL,
	[ModeloID] [INT] NOT NULL,
	[MarcaID] [INT] NOT NULL,
	[Matricula] [VARCHAR](50 )NOT NULL,
	[MillasRecorridas] [float] NOT NULL,
	[Asientos_ID] [INT] NOT NULL,
	
CONSTRAINT [PK_AVION_ID] PRIMARY KEY CLUSTERED 
(
	[AVION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

SELECT * FROM AVION;
DROP TABLE AVION;
INSERT INTO AVION VALUES (1,200,85.6,6,1,'P8',3544.20,1);