SELECT TIPO_SERVICIO.*
FROM TIPO_SERVICIO
WHERE TIPO_SERVICIO.TIPO_SERVICIO_ID = (SELECT SERVICIO.TIPO_DE_SERVICIOS_ID
										FROM SERVICIO
										WHERE SERVICIO.AVION_ID = ( SELECT VUELO.avionID
	    															FROM VUELO
																	WHERE VUELO.VUELO_ID = (SELECT BOLETO.VUELO_ID
																							FROM BOLETO, PASAJERO
																							WHERE BOLETO.PASAJERO_ID = (SELECT PASAJERO_ID
																														FROM PASAJERO
																														WHERE NOMBRE = 'PABLO CAMPOSECO')
																							AND BOLETO.FECHA_EMISION = (SELECT MAX(BOLETO.FECHA_EMISION)
																														FROM BOLETO, PASAJERO
																														WHERE BOLETO.PASAJERO_ID = (SELECT PASAJERO_ID
																																					FROM PASAJERO
																																					WHERE NOMBRE = 'PABLO CAMPOSECO')))))



														

--DESPLEGAR TODA LA INFORMACION DEL TIPO DE SERVICIO DEL ULTIMO AVION DONDE ESTUVO EL PASAJERO CON NOMBRE PABLO, ADJUNTAR EL PASAJERO_ID A LA CONSULTA.