CREATE TABLE SERVICIO(
[SERVICIO_ID][INT]NOT NULL,
[FECHA][DATETIME]NOT NULL,
[Avion_ID][INT]NOT NULL,
[TIPO_DE_SERVICIOS_ID][INT]NOT NULL
CONSTRAINT [PK_SERVICIO_ID] PRIMARY KEY CLUSTERED
(
	[SERVICIO_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
INSERT INTO SERVICIO VALUES (1,CONVERT(DATETIME,GETDATE()),1,1)
SELECT * FROM SERVICIO
DROP TABLE SERVICIO