CREATE TABLE TIPO_SERVICIO (
[TIPO_SERVICIO_ID][INT]NOT NULL,
[NOMBRE][VARCHAR](255)NOT NULL,
[AVION_ID][INT]NOT NULL,
[PRECIO][FLOAT]NOT NULL
CONSTRAINT [PK_TIPO_SERVICIO_ID] PRIMARY KEY CLUSTERED 
(
	[TIPO_SERVICIO_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
INSERT INTO TIPO_SERVICIO VALUES(1,'MANTENIMIENTO ESPECIAL 1',1,123.99)
SELECT * FROM TIPO_SERVICIO;
DROP TABLE TIPO_SERVICIO;