CREATE TABLE [VUELO](
	[VUELO_ID] [int] NOT NULL,
	[Status] [INT] NOT NULL,
	[Precio] [FLOAT] NOT NULL,
	[avionID] [int] NOT NULL,
	[rutaID] [VARCHAR](50) NOT NULL,
	[Fecha] [datetime] NOT NULL,
	[hAterrizaje] [datetime] NOT NULL,
	[hSalida] [datetime] NOT NULL,
	[hLlegada] [datetime] NOT NULL,
	[hDespegue] [datetime] NOT NULL
CONSTRAINT [PK_VUELO_ID] PRIMARY KEY CLUSTERED 
(
	[VUELO_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

INSERT INTO VUELO VALUES (1,1,120.99,1,'GAL123',CONVERT(DATETIME, '2017-09-17'),CONVERT(VARCHAR(8), GETDATE(), 108),CONVERT(VARCHAR(8), GETDATE(), 108),CONVERT(VARCHAR(8), GETDATE(), 108),CONVERT(VARCHAR(8), GETDATE(), 108))

SELECT * FROM VUELO;

DROP TABLE VUELO